name: zds_flutter_example

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.1.0
  intl: ^0.18.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  zds_flutter:
    path: ../
  flutter_quill: ^9.2.0
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.2
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.2.5
  zeta_flutter: ^0.4.0
  cross_file: ^0.3.3+8

flutter:
  uses-material-design: true
  assets:
    - assets/
