name: zds_flutter_example

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <3.16.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.1.0
  intl: ^0.18.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  zds_flutter:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/colors.json
