name: zds_flutter
description: Zebra Design System components for Flutter. A selection of UI components from Zebra Technologies.
version: 1.0.1
homepage: https://github.com/zebradevs/zds_flutter
repository: https://github.com/zebradevs/zds_flutter
issue_tracker: https://github.com/zebradevs/zds_flutter/issues

platforms:
  web:
  android:
  ios:
  macos:
  windows:
  linux:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <3.16.0"

dependencies:
  cached_network_image: ^3.2.1
  chewie: ^1.7.1
  collection: ^1.17.2
  cross_file: ^0.3.3+4
  csslib: ^0.17.3
  dropdown_button2: ^2.1.4
  expand_tap_area: ^1.1.0
  extended_image: ^8.1.0
  file_picker: ^5.1.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_html_audio: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_html_video: ^3.0.0-beta.2
  flutter_image_compress: ^2.0.4
  flutter_inappwebview: ^5.7.2+3
  flutter_layout_grid: ^2.0.5
  flutter_localizations:
    sdk: flutter
  flutter_quill: 7.4.16
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  flutter_swipe_action_cell: ^3.0.2
  giphy_get: ^3.5.0
  html: ^0.15.4
  http_client_helper: ^3.0.0
  image_editor_plus: ^1.0.3
  image_picker: ^1.0.2
  interval_time_picker: ^2.0.0+5
  intl: ^0.18.0
  linked_scroll_controller: ^0.2.0
  mime: ^1.0.0
  modal_bottom_sheet: ^3.0.0-pre
  open_filex: ^4.1.1
  path: ^1.8.0
  path_provider: ^2.0.2
  popover: ^0.2.6+2
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.3
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.10
  video_compress: ^3.1.0
  video_player: ^2.7.2
  vsc_quill_delta_to_html: ^1.0.3
  zeta_flutter: ^0.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lottie: ^2.1.0
  zds_analysis: ^1.0.0

flutter:
  assets:
    - lib/assets/images/
    - lib/assets/js/
    - lib/assets/animations/
    - lib/assets/fonts/selection.json
    - lib/assets/strings/
  fonts:
    - family: zds-icons
      fonts:
        - asset: lib/assets/fonts/zds.ttf
