name: zds_flutter
description: Zebra Design System components for Flutter. A selection of UI components from Zebra Technologies.
version: 0.2.0
homepage: https://github.com/zebradevs/zds_flutter
repository: https://github.com/zebradevs/zds_flutter
issue_tracker: https://github.com/zebradevs/zds_flutter/issues

platforms:
  web:
  android:
  ios:
  macos:
  windows:
  linux:

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  cached_network_image: ^3.2.1
  collection: ^1.16.0
  cross_file: ^0.3.3+4
  dropdown_button2: ^2.3.8
  expand_tap_area: ^1.1.0
  extended_image: ^8.0.2
  file_picker: ^5.1.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.6
  flutter_swipe_action_cell: ^3.0.2
  giphy_get: ^3.5.0
  http_client_helper: ^3.0.0
  image: ^4.0.15
  image_editor: ^1.3.0
  image_editor_plus: ^1.0.0
  image_picker: ^1.0.0
  interval_time_picker: ^2.0.0+5
  intl: ^0.18.0
  linked_scroll_controller: ^0.2.0
  mime: ^1.0.0
  modal_bottom_sheet: ^3.0.0-pre
  open_filex: ^4.3.2
  path: ^1.8.0
  path_provider: ^2.0.2
  popover: ^0.2.6+2
  table_calendar: ^3.0.3
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.10
  video_compress: ^3.1.0
  webview_flutter: ^4.2.4
  zeta_flutter: ^0.0.1+12

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lottie: ^2.1.0

flutter:
  assets:
    - lib/assets/images/
    - lib/assets/animations/
    - lib/assets/fonts/selection.json
    - lib/assets/strings/

  fonts:
    - family: zds-icons
      fonts:
        - asset: lib/assets/fonts/zds.ttf
